version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-app
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
